GroupManagement/PlayBall.GroupManagement/src/PlayBall.GroupManagement.Web/Models/GroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlayBall.GroupManagement.Web.Models
{
    public class GroupViewModel
    {
        public long Id { get; set; }
        public string Name { get; set; }
    }
}

GroupManagement/PlayBall.GroupManagement/src/PlayBall.GroupManagement.Web/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PlayBall.GroupManagement.Business.Services;
using PlayBall.GroupManagement.Web.Mappings;
using PlayBall.GroupManagement.Web.Models;

namespace PlayBall.GroupManagement.Web.Controllers
{
    [Route("groups")]
    public class GroupsController : Controller
    {
        private readonly IGroupsService _groupsService;

        public GroupsController(IGroupsService groupsService)
        {
            _groupsService = groupsService;
        }
        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            return View(_groupsService.GetAll().ToViewModel());
        }

        [HttpGet]
        [Route("{id}")]
        public IActionResult Details(long Id)
        {
            var group = _groupsService.GetById(Id);
            if (group == null)
            {
                return NotFound();
            }

            return View(group.ToViewModel());
        }

        [HttpPost]
        [Route("{id}")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(GroupViewModel model)
        {
            var group = _groupsService.Update(model.ToServiceModel());
            if (model == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("")]
        [ValidateAntiForgeryToken]
        public IActionResult CreateReally(GroupViewModel model)
        {
            _groupsService.Add(model.ToServiceModel());
            return RedirectToAction("Index");
        }
    }
}

GroupManagement/PlayBall.GroupManagement/src/PlayBall.GroupManagement.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PlayBall.GroupManagement.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GroupManagement/PlayBall.GroupManagement/src/PlayBall.GroupManagement.Web/Views/Groups/Create.cshtml
@model GroupViewModel

<form asp-controller="Groups" asp-action="CreateReally" method="post">
    <label asp-for="Name">Name</label>
    <input asp-for="Name" value="" />
    <button type="submit">Save</button>
</form>

GroupManagement/PlayBall.GroupManagement/src/PlayBall.GroupManagement.Web/Views/Groups/Details.cshtml
@model GroupViewModel

<form asp-controller="Groups" asp-action="Edit" asp-route-id="@Model.Id" method="post">
    <label asp-for="@Model.Name">@Model.Name</label>
    <input asp-for="@Model.Name" value="@Model.Name" />
    <button type="submit">Save</button>
</form>

GroupManagement/PlayBall.GroupManagement/src/PlayBall.GroupManagement.Web/Views/Groups/Index.cshtml
@model IEnumerable<GroupViewModel>

<a asp-controller="Groups" asp-action="Create">Create</a>
<ul>
    @foreach (var group in Model)
    {
        <li>
            @group.Name
            <a asp-controller="Groups" asp-action="Details" asp-route-id="@group.Id">Edit</a>
        </li>
    }
</ul>

GroupManagement/PlayBall.GroupManagement/src/PlayBall.GroupManagement.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Hello World</h1>

GroupManagement/PlayBall.GroupManagement/src/PlayBall.GroupManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>